# Generated by Django 4.0 on 2021-12-13 02:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reward', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 12, 12, 20, 52, 4, 706031), editable=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WORKING', 'Working'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Canceled')], default='NEW', max_length=10)),
                ('completed_on', models.DateTimeField(null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', related_query_name='assignment', to='auth.user')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 12, 12, 20, 52, 4, 706031), editable=False)),
                ('bounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bounty')),
            ],
        ),
    ]
