# Generated by Django 4.0 on 2021-12-23 03:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0005_alter_bounty_created_on_alter_invoice_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounty',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 21, 12, 28, 230492), editable=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 21, 12, 28, 231492), editable=False),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 12, 22, 21, 12, 28, 232492), editable=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('bounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bounty')),
            ],
        ),
    ]
