# Generated by Django 4.0 on 2022-01-26 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_application_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='category',
            field=models.CharField(choices=[('MISC', 'Miscellaneous'), ('ART', 'Visual Arts'), ('AUDIO', 'Audio and Music'), ('BUSINESS', 'Business and Marketing'), ('EDUCATION', 'Education'), ('LIFESTYLE', 'Lifestyle'), ('TECHNOLOGY', 'Technology'), ('VIDEO', 'Video and Editing'), ('WRITING', 'Writing and Literature')], default='MISC', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 20, 14, 50, 661609), editable=False),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 20, 14, 50, 661609), editable=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 20, 14, 50, 661609), editable=False),
        ),
    ]
