# Generated by Django 4.0 on 2022-01-26 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_bounty_category_alter_application_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='tags',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 20, 28, 57, 162482), editable=False),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 20, 28, 57, 161481), editable=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 20, 28, 57, 162482), editable=False),
        ),
    ]
