# Generated by Django 3.2.8 on 2021-10-31 02:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=50, unique=True)),
                ('portfolio_links', models.TextField(blank=True)),
                ('balance', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounty_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('reward', models.IntegerField()),
                ('project_link', models.CharField(max_length=50)),
                ('due_date', models.DateTimeField()),
                ('created_on', models.DateTimeField()),
                ('completed_on', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Available'), (2, 'Working'), (3, 'Complete'), (4, 'Paid'), (5, 'Cancelled')])),
                ('contracts', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satearn_api.organization')),
                ('earner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satearn_api.earner')),
            ],
        ),
    ]
